version: '3.8'
services:
  postgres:
    image: postgres
    container_name: shopswift_product_db
    environment:
      POSTGRES_DB: shopswift_product
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: